#! /bin/bash

fbuild() {
	fmkrdfs
	make all && sudo make
	chown senko hdd.img kernel.bin initrd.img
}

fmkrdfs() {
	sudo dd if=/dev/zero of=initrd.img count=16484
	sudo mkfs.ext2 -F initrd.img
	sudo mount -o loop initrd.img ./hdd
	sudo cp -R ./rdfs/hello.txt ./hdd/ 		#FIXME!
	sudo umount ./hdd
}

CFILE=`readlink -e "$0"`
CDIR=`dirname "$CFILE"`

cd "$CDIR"
#echo $USER


case $1 in
--debug | -d)
	fbuild
	
	sudo qemu-system-i386 -s -S -hda hdd.img &
	cgdb kernel.bin.dbg
	;;
--rebuild | -R)
	make rebuild
	chown senko hdd.img kernel.bin
	;;
--build | -b)
	fbuild
	;;
--mk-initrd | -i)
	fmkrdfs
	;;
--clean | -c)
	make clean
	;;
--run | -r)
	fbuild
	sudo qemu-system-i386 -hda hdd.img
	;;
--write | -w)
	fbuild
	
	if [ $2 -e '--reboot' ] && [ $# = 3 ] ; then
		sudo dd if=./hdd.img of=$3
		sudo reboot
	elif [ $# = 2 ] ; then
		sudo dd if=./hdd.img of=$2
	else
		echo "Invalid parameters!"
	fi
	;;
--help | -h | *)
	echo \
	"Использование: $0 [OPTION]...
Сборка образа ОС.

Options:
  -d, --debug 	             run OS in debug mode with cgdb
  -b, --build                build OS and image
  -R, --rebuild              rebuild OS and image
  -w, --write                write OS image
  -r, --run  	             run OS on emulator
  -c, --clean	             clean object and executable files (do make clean)
  -h, --help                 display this help and exit
  --mk-initrd                make initrd"
	;;
*)
	fbuild
	;;
esac



#if [ $1 = "debug" ] ; then
#elif [ $1 = "rebuild" ] ; then
#elif [ $1 = "clean" ] ; then
#	make clean
#elif [ $1 = "-r" ] ; then
#elif [ $1 = "write" ] ; then
#else
#fi
#sudo dd if=./hdd.img of=/dev/sdb
